[package]
name = "kernel-5_10"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[package.metadata.build-package]
package-name = "kernel-5.10"

[lib]
path = "../packages.rs"

[[package.metadata.build-package.external-files]]
# Use latest-kernel-srpm-url.sh to get this.
url = "https://cdn.amazonlinux.com/blobstore/f23a0c9ea605c78f33dd6ee85972cd11eb4353ae23abfe9b434756a645844cb4/kernel-5.10.234-225.895.amzn2.src.rpm"
sha512 = "28e5955eb206be1c01cc262d2681dd0b9fb6e9d9f78ae70cf6af9d89e32a1fb1e3e2704c4123ecf6fabd3bb4211d536058c8e2c3005447983ccc4c3d5fe9e29a"
force-upstream = true

[[package.metadata.build-package.external-files]]
# Use latest-neuron-srpm-url.sh to get this.
url = "https://yum.repos.neuron.amazonaws.com/aws-neuronx-dkms-2.19.64.0.noarch.rpm"
sha512 = "f93aa097ea0515533817ce9737810cb8b025c35c3d4367c2e667292c0692d525ffbc9b7972fe957174e206a82e394cc7e076e5b399e1050f2c5f6ed129d4d739"
force-upstream = true

[build-dependencies]
microcode = { path = "../microcode" }
