[package]
name = "kernel-6_1"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[package.metadata.build-package]
package-name = "kernel-6.1"

[lib]
path = "../packages.rs"

[[package.metadata.build-package.external-files]]
# Use latest-kernel-srpm-url.sh to get this.
url = "https://cdn.amazonlinux.com/al2023/blobstore/ffe00924daa42edd797a396d01fb21af95701161e56f101e909ddd3f70c830ef/kernel-6.1.128-136.201.amzn2023.src.rpm"
sha512 = "fab5bc1eb2c00bb5fece465614cc887fdf5c358237399b062bd2530a5580b56386dc830ded56247037618ae8990dcdef5303f2df27edce1da3e89deaeaf08ad7"
force-upstream = true

[[package.metadata.build-package.external-files]]
# Use latest-neuron-srpm-url.sh to get this.
url = "https://yum.repos.neuron.amazonaws.com/aws-neuronx-dkms-2.19.64.0.noarch.rpm"
sha512 = "f93aa097ea0515533817ce9737810cb8b025c35c3d4367c2e667292c0692d525ffbc9b7972fe957174e206a82e394cc7e076e5b399e1050f2c5f6ed129d4d739"
force-upstream = true

[build-dependencies]
microcode = { path = "../microcode" }
